CREATE TABLE IF NOT EXISTS NOBLE_WIN (
    YEAR INTEGER,
    SUBJECT TEXT,
    WINNER TEXT,
    COUNTRY TEXT,
    CATEGORY TEXT
);

INSERT INTO NOBLE_WIN (YEAR, SUBJECT, WINNER, COUNTRY, CATEGORY) VALUES
    (1978, 'PHYSICS', 'HANNES ALFVEN', 'SWEDEN', 'SCIENTIST'),
    (1978, 'PHYSICS', 'ZAINAB WASIF', 'RUSSIA', 'SCIENTIST'),
    (1971, 'BIOLOGY', 'ZUBIA IMRAN', 'FRANCE', 'SCIENTIST'),
    (1979, 'BIOLOGY', 'FASEEHA SHAFIQU', 'GERMANY', 'SCIENTIST'),
    (1975, 'PHYSIOLOGY', 'SHARMEEN SHEIKH', 'FRANCE', 'SCIENTIST'),
    (2000, 'MATHEMATICS', 'AYESHA AZEEMI', 'PAKISTAN', 'MATHEMATICIAN');

SELECT * FROM NOBLE_WIN WHERE SUBJECT NOT LIKE 'P%';